# Generated by Django 5.1.3 on 2024-11-27 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('user_profiles', '0004_alter_profilefollowingmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='liked_users',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='title',
        ),
        migrations.CreateModel(
            name='PostLikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='posts.postmodel')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_users', to='user_profiles.profilemodel')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user_profile', 'liked_post'), name='unique_likes')],
            },
        ),
    ]
