# Generated by Django 5.1.3 on 2024-11-25 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_postmodel_liked_users_postlikemodel'),
        ('user_profiles', '0004_alter_profilefollowingmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlikemodel',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_users', to='user_profiles.profilemodel'),
        ),
    ]
