# Generated by Django 5.1.3 on 2024-11-27 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentLikeModel',
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
