# Generated by Django 5.1.3 on 2024-11-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_profilefollowingmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilefollowingmodel',
            options={'ordering': ['created_at']},
        ),
        migrations.AddConstraint(
            model_name='profilefollowingmodel',
            constraint=models.UniqueConstraint(fields=('user_profile', 'following_user_id'), name='unique_followers'),
        ),
    ]
