# Generated by Django 5.1.3 on 2024-11-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_alter_profilefollowingmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilefollowingmodel',
            options={'ordering': ['-created_at']},
        ),
    ]
